/*
 *  LICENSE INFORMATION:
 */
package de.alexanderlindhorst.sonar.checkstyle.plugin.options.gui;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Set;

import org.openide.util.Exceptions;
import org.openide.util.Utilities;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.collect.Sets;

import javax.swing.JFileChooser;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author lindhrst
 */
public class SonarCheckstylePluginConfigPane extends javax.swing.JPanel {

    private static final Logger LOGGER = LoggerFactory.getLogger(SonarCheckstylePluginConfigPane.class);
    private static final long serialVersionUID = 1L;
    private final Set<ChangeListener> changeListeners = Sets.newHashSet();

    /**
     * Creates new form SonarCheckstylePluginConfigPane
     */
    public SonarCheckstylePluginConfigPane() {
        initComponents();
    }

    /* Event handling */
    public void addChangeListener(ChangeListener changeListener) {
        changeListeners.add(changeListener);
        changeListener.stateChanged(new ChangeEvent(this));
    }

    public void removeChangeListener(ChangeListener changeListener) {
        changeListeners.remove(changeListener);
    }

    private void fireStateChanged() {
        ChangeEvent event = new ChangeEvent(this);
        for (ChangeListener changeListener : changeListeners) {
            changeListener.stateChanged(event);
        }
    }

    /* properties */
    public void setConfigUrl(URL url) {
        urlField.setText(url == null ? null : url.toExternalForm());
    }

    public URL getConfigUrl() throws MalformedURLException {
        String givenUrl = urlField.getText();
        if (givenUrl == null || givenUrl.isEmpty()) {
            return null;
        }
        return new URL(urlField.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.JLabel label = new javax.swing.JLabel();
        urlField = new javax.swing.JTextField();
        fileChooserButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(label, org.openide.util.NbBundle.getMessage(SonarCheckstylePluginConfigPane.class, "SonarCheckstylePluginConfigPane.label.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(label, gridBagConstraints);

        urlField.setText(org.openide.util.NbBundle.getMessage(SonarCheckstylePluginConfigPane.class, "SonarCheckstylePluginConfigPane.urlField.text")); // NOI18N
        urlField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                urlFieldChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 2.0;
        add(urlField, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(fileChooserButton, org.openide.util.NbBundle.getMessage(SonarCheckstylePluginConfigPane.class, "SonarCheckstylePluginConfigPane.fileChooserButton.text")); // NOI18N
        fileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        add(fileChooserButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void fileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserButtonActionPerformed
        LOGGER.debug("Choosing config from file system");
        JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView());
        int selectedOption = fileChooser.showOpenDialog(null);
        if (selectedOption == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = fileChooser.getSelectedFile();
                LOGGER.debug("selected config file is {}", selectedFile);
                setConfigUrl(Utilities.toURI(selectedFile).toURL());
            } catch (MalformedURLException ex) {
                Exceptions.printStackTrace(ex);
            }
        }
    }//GEN-LAST:event_fileChooserButtonActionPerformed

    private void urlFieldChanged(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_urlFieldChanged
        fireStateChanged();
    }//GEN-LAST:event_urlFieldChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JTextField urlField;
    // End of variables declaration//GEN-END:variables
}
